### ISSUE TITLE
Multiple Vulnerabilities Introduced by dependencies

### ISSUE THREAD

**Issue by danielobasi** [Flutterwave/Node#103]
<img width="594" alt="flutterwave_issue" src="https://user-images.githubusercontent.com/2592817/220440289-ccc26e8a-8a7d-4531-8d3b-0740417cdaa0.png">
 I have been looking for the endpoints to implement  your API without this library for now, just can't find it,  can I get a link to it? I want to take payment, verify/resolve  bank accounts, add sub_accounts and split payments .

**Comment by corneliusyaovi** [comment]
Hi @danielobasi, We appreciate you sharing this with us. We have released a new version that addresses the issue you raised here. Kindly update your library to v1.1.3 to get the changes.

**Comment by danielobasi** [comment]
Great!!
