### ISSUE TITLE
Transfer Retries not working

### ISSUE THREAD

**Issue by akwotom** [Flutterwave/Node#106]
Have you read our [Code of Conduct](https://github.com/Flutterwave/Python/blob/master/CONTRIBUTING.md)? By filing an Issue, you are expected to comply with it, including treating everyone with respect.

# Description

The SDK doesn't provide a way to retry a payout

# Steps to Reproduce
Just install

1. 
2. 
3. 

## Reproduces how often

# Configuration
- API Version: 
- Environment: 
- Browser: 
- Language: 

# Additional Information

**Comment by Dekunledev** [comment]
Hi @akwotom,

The Retry Transfer (payout) feature is currently not available on the Flutterwave Node v3 SDK. Nonetheless, several missing features including the Retry Transfer feature will be added to the SDK.

However, you can find [here](https://developer.flutterwave.com/docs/collecting-payments/standard#step-2-get-a-payment-link) a detailed sample of a request to Retry a Transfer (payout) without using the SDK.

**Comment by akwotom** [comment]
Even bearer authentication doesn't work.

**Comment by Dekunledev** [comment]
See [here](https://developer.flutterwave.com/docs/integration-guides/authentication#authorizing-api-calls) full details and guide on how to authorise api calls
