### ISSUE TITLE
Cannot Verify a Transaction 

### ISSUE THREAD

**Issue by chuksonu700** [Flutterwave/Node#111]
Description

When I try Calling the Transaction.verify function to verify a transaction it fails
which I feel is from the base ULR not specified within the module flutterwave-v3 module

# Steps to Reproduce
Just call the below function

```
const Flutterwave = require('flutterwave-node-v3');

const flw = new Flutterwave(FLW_PUBLIC_KEY,FLW_SECRET_KEY);
 flw.Transaction.verify({
    id: transactionId,
  });
```

## Expected behaviour

it Should return a JSON containing the transaction details like this
```
{
  "status": "success",
  "message": "Transaction fetched successfully",
  "data": {
    "id": 1163068,
    "tx_ref": "akhlm-pstmn-blkchrge-xx6",
    "flw_ref": "FLW-M03K-02c21a8095c7e064b8b9714db834080b",
    "device_fingerprint": "N/A",
    "amount": 3000,
    "currency": "NGN",
    "charged_amount": 3000,
    "app_fee": 1000,
    "merchant_fee": 0,
    "processor_response": "Approved",
    "auth_model": "noauth",
    "ip": "pstmn",
    "narration": "Kendrick Graham",
    "status": "successful",
    "payment_type": "card",
    "created_at": "2020-03-11T19:22:07.000Z",
    "account_id": 73362,
    "amount_settled": 2000,
    "card": {
      "first_6digits": "553188",
      "last_4digits": "2950",
      "issuer": " CREDIT",
      "country": "NIGERIA NG",
      "type": "MASTERCARD",
      "token": "flw-t1nf-f9b3bf384cd30d6fca42b6df9d27bd2f-m03k",
      "expiry": "09/22"
    },
    "customer": {
      "id": 252759,
      "name": "Kendrick Graham",
      "phone_number": "0813XXXXXXX",
      "email": "user@example.com",
      "created_at": "2020-01-15T13:26:24.000Z"
    }
  }
}
```

## Actual behaviour
Cannot Get Error

## Reproduces how often
all the time

# Configuration
- API Version:  v3 
- Environment: test mode 
- Language:  Node X.X  

Additional
When a try running a get request using my API credentials it works, which my current Work around it. Thanks love your Work
![flutterwave error](https://user-images.githubusercontent.com/48865921/226391048-fbb6e91c-c6dc-48bf-a841-e3d6ced6211a.png)

**Comment by oluway** [comment]
You may call the API direct using Axios or fetch

**Comment by corneliusyaovi** [comment]
Hello @chuksonu700, 

This has been fixed in the latest release of this package, please update your library to v1.1.3 and retry the verify call.
