### ISSUE TITLE
Plan Duration is Optional but Enforced by  Morx

### ISSUE THREAD

**Issue by mugendi** [Flutterwave/Node#44]
When creating plans using the javascript client, an error is thrown by Morx when duration is not set:

```
(node:36522) UnhandledPromiseRejectionWarning: Error: duration is required
    at throwErrorWhen (/home/mugz/projects/node/unto/node_modules/morx/lib/morx.param.extractor.js:61:9)
```

This functionality contradicts the [API documentation](https://developer.flutterwave.com/docs/payment-plans#how-to-create-a-payment-plan) which clearly indicates that this parameter is optional.

What is the position. Is duration optional or not?

**Comment by Corvus97** [comment]
Hello @mugendi,

Thank you for sharing your experience with us. We are sorry for taking so long to get back to you.

We have reviewed this issue and resolved it. You should be able to create plans for your product without specifying its duration.

If you have any questions, you can shoot us an [email](mailto:developers@flutterwavego.com) or send us a message on our [developer slack](https://bit.ly/34Vkzcg).
