### ISSUE TITLE
Support 

### ISSUE THREAD

**Issue by SaintGalileo** [Flutterwave/Node#72]
Does it sdk  support expo on react native

**Comment by opeolluwa** [comment]
> Does it sdk support expo on react native

I don't think so @SaintGalileo. What yo can do is build a backend for you expo/ react native project then make API calls or use the React native SDk [https://developer.flutterwave.com/docs/sdks-and-plugins/mobile-libraries](https://developer.flutterwave.com/docs/sdks-and-plugins/mobile-libraries) I hope this helps

**Comment by Corvus97** [comment]
Hi @SaintGalileo,

Thank you for the question. 

Like @opeolluwa advised, you can use this for your backend to make the API calls. If you are interested in our integration for mobile (cross-platform), you can use our [react-native library](https://github.com/Flutterwave/React-Native).

If you have any questions, kindly send us an [email](mailto:developers@flutterwavego.com) or send us a message on our [developer slack](https://bit.ly/34Vkzcg).
