### ISSUE TITLE
Amount is required for payment plan creation

### ISSUE THREAD

**Issue by Gbahdeyboh** [Flutterwave/Node#87]
When creating a payment plan, the amount field is required. See [here](https://github.com/Flutterwave/Node/blob/master/services/payment-plans/rave.create.js#L8)

In the documentation, it says there is an option for using [dynamic amounts](https://developer.flutterwave.com/docs/recurring-payments/payment-plans/#dynamic-amounts) in which you do not need to specify an amount when creating the payment plan. 

<img width="811" alt="Screenshot 2022-10-09 at 1 46 29 PM" src="https://user-images.githubusercontent.com/29985200/194757614-6358373d-1954-47ff-b167-92b1e4eb101b.png">

**Comment by corneliusyaovi** [comment]
Hello @Gbahdeyboh, kindly update your library to v1.1.3. We have made the required change to the library.
